# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
    deploy_to_psgallery:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          name: Checkout repository
        - uses: pcgeek86/publish-powershell-module-action@v19
          name: Publish Module to PowerShell Gallery
          id: publish-module
          with:
            modulePath: TeslaMatrix
            NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }} 
    

      
